Repository camptocamp/c2cgeoportal, pull requests merged in 2020-07, with the labels that each got.

#6653 Add missing geotablePrimaryKey metadata
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
Labels: backport 2.5, backport master

#6660 Typo, Send the welcome email
  doc/integrator/extend_data_model.rst
Labels: backport 2.4, backport master

#6676 Clarify creation documentation
  doc/integrator/create_application.rst.tmpl
Labels: backport master

#6684 Doc: fix typos
  doc/integrator/create_application.rst.tmpl
Labels: backport master

#6715 Set the versions in the runner
  .github/workflows/qgis.yaml
  Dockerfile
Labels: backport master

#6718 Don't update the changelog on QGIS CI
  ci/publish
Labels: backport master

#6724 Add getitfixed alembic
  Pipfile
  Pipfile.lock
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/alembic.ini
Labels: backport master

#6727 Doc 2.5 add minimum requirement for migration
  doc/integrator/upgrade_application.rst.tmpl
Labels: backport master

#6737 Fix eslint error
  ci/create-new-project
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
Labels: backport master

#6736 Add ending slash redirect on /getitfixed_admin
  geoportal/c2cgeoportal_geoportal/__init__.py
Labels: backport master
