Repository camptocamp/c2cgeoportal, pull requests merged in 2020-12, with the labels that each got.

#7353 Do not add layer to theme if GetCapabilities fails
  docker-compose.yaml
  docker/test-tilecloudchain/config.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/tests/functional/__init__.py
  geoportal/tests/functional/test_themes_dimensions.py
  geoportal/tests/functional/test_themes_edit_columns.py
  geoportal/tests/functional/test_themes_entry.py
  geoportal/tests/functional/test_themes_metadata.py
  geoportal/tests/functional/test_themes_time.py
Labels: backport master

#7448 Add USER_ID and ROLE_IDS in lingua extractor requests
  geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
Labels: backport master

#7456 Add Python version for the audit
  ci/config.yaml
Labels: backport 2.4

#7489 Push the right image
  .github/workflows/main.yaml
Labels: backport master

#7488 Gunicorn: adapt tmpdir setting for Docker environment
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+env.mako_tmpl
Labels: backport 2.5, backport master

#7506 Fix publish
  .github/workflows/main.yaml
  ci/publish
  scripts/get-version
Labels: backport master

#7510 Fix time on wms layer groups
  doc/administrator/wmstime.rst
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/tests/functional/test_themes_time.py
Labels: backport master
