Repository camptocamp/c2cgeoportal, pull requests merged in 2020-11, with the labels that each got.

#7198 Fix geo_table with environment variables
  geoportal/c2cgeoportal_geoportal/views/layers.py
Labels: backport master

#7209 Fix PR lint action
  .github/workflows/pr-title-lint.yaml
Labels: backport 2.4, backport 2.5

#7277 Fix documentation links
  doc/index.rst.tmpl
Labels: backport master

#7282 Changelog fix
  ci/changelog
Labels: backport master

#7306 Doc - Explain how to extend ngeo
  doc/integrator/ngeo.rst.mako
Labels: backport 2.5, backport master
