Repository camptocamp/c2cgeoportal, pull requests merged in 2020-09, with the labels that each got.

#6924 Fix missing i10n file for theme2fts
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
Labels: backport master

#6916 Move the base application configuration in the Makefile
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Makefile_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
Labels: backport master

#6943 Fix pdfreport call
  geoportal/c2cgeoportal_geoportal/views/pdfreport.py
  geoportal/c2cgeoportal_geoportal/views/proxy.py
Labels: backport 2.5, backport master

#6947 Add pdfreport to vars
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Labels: backport 2.5, backport master

#6961 Publish project Docker images to GitHub Container Registry
  Pipfile
  ci/Pipfile
  ci/Pipfile.lock
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/ci.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+prospector.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/scripts/publish-docker
Labels: backport 2.4, backport master

#6984 Do not request DescribeFeatureType if not OGCServer.wfs_support
  geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
Labels: backport 2.4, backport master

#7015 More compatible with VSCode auto format
  geoportal/c2cgeoportal_geoportal/scaffolds/create/yamllint.yaml
  yamllint.yaml
Labels: backport 2.5

#7016 Sometimes the upload failed
  ci/publish-pypi
Labels: backport master

#7041 Fix typo in the documentation
  doc/integrator/filter.rst.tmpl
Labels: backport master
