Repository camptocamp/c2cgeoportal, pull requests merged in 2020-06, with the labels that each got.

#6439 Remove, no more valid
  doc/administrator/mapfile.rst
Labels: backport master

#6374 Fix DB sessions timeouts
  .github/workflows/qgis.yaml
  docker-compose.yaml
  docker/qgisserver/acceptance-tests/acceptance-tests
  docker/qgisserver/docker-compose.yaml
  docker/qgisserver/geomapfish_qgisserver/accesscontrol.py
  docker/qgisserver/tests/functional/accesscontrol_allow_to_edit_test.py
  docker/qgisserver/tests/functional/accesscontrol_test.py
  docker/qgisserver/tests/functional/conftest.py
Labels: backport master

#6465 Add get_settings used by c2cwsgiutils
  geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
Labels: backport 2.5, backport master

#6503 Fix pypi deployment
  ci/publish
Labels: backport master

#6500 Upgrade c2cgeoform to 2.1.14
  Pipfile
  Pipfile.lock
  admin/c2cgeoportal_admin/views/layers_wms.py
  admin/c2cgeoportal_admin/views/layers_wmts.py
Labels: backport master

#6499 Fix Extend the data model documentation
  doc/integrator/extend_data_model.rst
Labels: backport master

#6522 Hide the ID in the form
  doc/integrator/extend_data_model.rst
Labels: backport master

#6521 Fix environment variable name
  geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.tmpl
Labels: backport master

#6534 Fix include/exclude in admin interface
  admin/c2cgeoportal_admin/routes.py
  admin/config.yaml
  admin/tests/tests.yaml
  doc/integrator/admin_interface.rst
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
Labels: backport master

#6548 Update the extend the data model for 2.5
  doc/integrator/extend_data_model.rst
Labels: backport master

#6565 [admin] Support undefined metadatas
  admin/c2cgeoportal_admin/schemas/metadata.py
  admin/c2cgeoportal_admin/templates/widgets/metadata.pt
  admin/tests/test_metadatas.py
Labels: backport master

#6579 Some small fix in the documentations
  doc/administrator/mapfile.rst
  doc/integrator/objectstorage.rst
  doc/integrator/tilegeneration.rst
Labels: backport 2.5, backport master

#6598 Use the same image name in publish as in the build
  geoportal/c2cgeoportal_geoportal/scaffolds/create/scripts/publish-docker
Labels: backport 2.5

#6652 Fix image name
  geoportal/c2cgeoportal_geoportal/scaffolds/create/scripts/publish-docker
Labels: backport 2.5
