Repository camptocamp/c2cgeoportal, pull requests merged in 2020-10, with the labels that each got.

#7065 Fix the max age
  geoportal/c2cgeoportal_geoportal/lib/authentication.py
Labels: backport 2.4, backport 2.5

#7069 Fix pdfreport reading content
  geoportal/c2cgeoportal_geoportal/views/pdfreport.py
Labels: backport 2.5, backport master

#7039 Fix: update-po doesn't use PGSCHEMA defined in .env file
  geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl
Labels: backport 2.5

#7076 Fix the geoportal image send
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/ci.yaml_tmpl
Labels: backport master

#7083 Fix call to manage users
  geoportal/c2cgeoportal_geoportal/scripts/manage_users.py
  geoportal/setup.py
Labels: backport master

#7137 Bump pr-lint-action to fix it
  .github/workflows/pr-title-lint.yaml
Labels: backport 2.4, backport 2.5

#7117 Fix space in redirect URL
  geoportal/c2cgeoportal_geoportal/views/dynamic.py
  geoportal/tests/functional/test_dynamicview.py
Labels: backport 2.4, backport 2.5

#7161 Remove Webpack progress mode
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
Labels: backport master

#7168 Fix build command in documentation
  doc/developer/server_side.rst.tmpl
Labels: backport master
