Repository camptocamp/c2cgeoportal, pull requests merged in 2021-11, with the labels that each got.

#8860 Add generic migration changes for 2.5
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Labels: backport master, backport 2.6

#8877 Add generic migration changes for 2.6
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Labels: backport master

#8879 Don't audit the develop part
  ci/config.yaml
Labels: backport 2.6

#8874 Do not add layers in themes in synchronize
  admin/c2cgeoportal_admin/lib/ogcserver_synchronizer.py
  admin/tests/lib/test_ogcserver_synchronizer.py
Labels: backport master

#8907 Add information about default action in the full-text search
  doc/integrator/fulltext_search.rst
Labels: backport master

#8924 Audit 2.4, see commits ...
  admin/npm-cve-ignore
  ci/config.yaml
  geoportal/npm-cve-ignore
Labels: backport master, backport 2.5, backport 2.6

#8935 Mouse position option typo for WGS84
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
Labels: backport master

#8942 Ignore some new CVE
  ci/config.yaml
  npm-cve-ignore
Labels: backport master, backport 2.5, backport 2.6

#8885 Fix code verification in oauth2
  geoportal/c2cgeoportal_geoportal/lib/oauth2.py
Labels: backport master

#8962 Better error when the result is not a JSON
  doc/integrator/make.rst.tmpl
  geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Labels: backport master
