Repository camptocamp/c2cgeoportal, pull requests merged in 2021-03, with the labels that each got.

#7882 Doc - Add custom alembic
  doc/administrator/mapfile.rst
  doc/developer/cache.rst
  doc/developer/custom_alembic.rst
  doc/developer/debugging.rst
  doc/developer/index.rst
  doc/developer/server_side.rst.tmpl
  doc/integrator/backend_qgis.rst
  doc/integrator/create_application.rst.tmpl
  doc/integrator/functionality.rst
  doc/integrator/requirements.rst
Labels: backport 2.6, backport master

#7886 Update the changelog
  build.mk
  ci/test-new-project
  ci/waitwsgi
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+dot+eslintrc_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+dot+prospector.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Labels: backport master

#7890 Use pipenv sync
  .dependabot/config.yml
  Dockerfile
  Makefile
  doc/Dockerfile
  docker/qgisserver/Dockerfile
  docker/qgisserver/requirements.txt
Labels: backport master

#7881 Remove default URL length limit in Gunicorn
  geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl
Labels: backport 2.5, backport 2.6

#7897 Move ngeoScaleSelectorOptions and gmfMousePositionOptions on desktop,…
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7919 Remove override with the same value, better format
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
Labels: backport master

#7903 Add doc about excluded or readonly attributes while editing
  doc/administrator/administrate.rst.tmpl
  doc/administrator/editing.rst
Labels: backport 2.4, backport 2.5, backport 2.6

#7918 Make shortener not allowed host exception more explicit
  geoportal/c2cgeoportal_geoportal/views/shortener.py
Labels: backport 2.6, backport master

#7907 Add some missing entrypoint
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7920 Don't have the vars diff in ngeo and create diff
  geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Labels: backport master

#7938 Fix unworking alternate_projections behivior
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7958 Fix dupplicate, unsplited coordinates
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7962 Remove defined but never used
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
Labels: backport master

#7981 Fix filter on private layers
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport 2.6, backport master

#7980 Some little fix
  .gitignore
  CHANGELOG.md
  ci/changelog.yaml
  geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
  geoportal/c2cgeoportal_geoportal/views/proxy.py
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport master

#7984 Add measure point to update_path
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
Labels: backport master

#7982 Add more information in the ChangeLog
  geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/env.project_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/tilegeneration/config.yaml.tmpl_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Labels: backport master

#7991 Fix the create application
  doc/integrator/create_application.rst.tmpl
Labels: backport master

#7971 Highlight style for points
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7994 Pull the base images before building the image
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport 2.5, backport master

#8005 Don't use the --pull in CI
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport 2.5, backport 2.6

#8013 CI is lower on GitHub
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport 2.5, backport master

#8017 Add missing default value
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport 2.5, backport master

#8006 Be able to configure the pool on OpenShift
  geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7955 Add OAuth2 authentication server
  .pylintrc
  Pipfile
  Pipfile.lock
  admin/c2cgeoportal_admin/routes.py
  admin/c2cgeoportal_admin/views/oauth2_clients.py
  commons/c2cgeoportal_commons/alembic/static/7ef947f30f20_add_oauth2_tables.py
  commons/c2cgeoportal_commons/models/static.py
  doc/integrator/authentication.rst
  doc/integrator/authentication_oauth2.rst
  doc/integrator/security.rst
  docker/test-tilecloudchain/config.yaml
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/lib/authentication.py
  geoportal/c2cgeoportal_geoportal/lib/oauth2.py
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/templates/login.html
  geoportal/c2cgeoportal_geoportal/templates/notlogin.html
  geoportal/c2cgeoportal_geoportal/views/login.py
  geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
  geoportal/c2cgeoportal_geoportal/views/memory.py
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/tests/__init__.py
  geoportal/tests/functional/__init__.py
  geoportal/tests/functional/test_entry.py
  geoportal/tests/functional/test_login.py
  geoportal/tests/functional/test_mobile_desktop.py
  geoportal/tests/functional/test_oauth2.py
  geoportal/tests/functional/test_themes.py
  geoportal/tests/functional/test_themes_dimensions.py
  geoportal/tests/functional/test_themes_edit_columns.py
  geoportal/tests/functional/test_themes_editing.py
  geoportal/tests/functional/test_themes_entry.py
  geoportal/tests/functional/test_themes_layermultinameerror.py
  geoportal/tests/functional/test_themes_mixed.py
  geoportal/tests/functional/test_themes_nameerror.py
  geoportal/tests/functional/test_themes_private.py
  geoportal/tests/functional/test_themes_scale.py
  geoportal/tests/functional/test_themes_time.py
Labels: backport master

#8007 Add documentation for the simple application mode
  doc/integrator/admin_interface.rst
  doc/integrator/create_application.rst.tmpl
  doc/integrator/extend_data_model.rst
  doc/integrator/index.rst
  doc/integrator/internationalization.rst
  doc/integrator/make.rst.tmpl
  doc/integrator/multiple_databases.rst
  doc/integrator/ngeo.rst.tmpl
  doc/integrator/ngeo_new_interface.rst
  doc/integrator/structure.rst
Labels: backport master

#8012 Fix admin i18n in simple application mode
  Dockerfile
  bin/build-l10n
  geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport master

#8020 Fix entrypoint in haproxy
  docker/config/haproxy/haproxy.cfg.tmpl
Labels: backport master

#8021 Put the command in quote to be clearer
  geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Labels: backport 2.6

#8023 Fix open pull request in changelog
  ci/changelog
Labels: backport 2.5, backport master

#8032 Have Redis cli in the tool container
  Dockerfile
Labels: backport master
