Repository camptocamp/c2cgeoportal, pull requests merged in 2021-04, with the labels that each got.

#8031 Add tests for admin OAuth2 clients
  admin/tests/test_oauth2_clients.py
Labels: backport master

#8010 Build an CI simple mode auto detection
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/main.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport master

#8038 Fix OAuth2 authentication
  geoportal/c2cgeoportal_geoportal/lib/authentication.py
Labels: backport master

#8043 Fix l10n generation
  bin/build-l10n
Labels: backport master

#8045 Allows the attributes from the WFS DescribeFeatures to be None
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport 2.5, backport master

#8011 Move scaffold variable from docker-compose* to the env.default file
  geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.override.sample.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl
Labels: backport master

#8046 Allows nearly all variable to be from environment variable
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#8036 Make standard roles customisable
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/lib/__init__.py
  geoportal/c2cgeoportal_geoportal/lib/functionality.py
  geoportal/tests/__init__.py
  geoportal/tests/functional/test_login.py
  geoportal/tests/functional/test_themes_loop.py
Labels: backport master

#8058 Force new release on build from ngeo
  .github/workflows/ngeo-25.yaml
  .github/workflows/ngeo-26.yaml
  scripts/get-version
Labels: backport 2.5, backport 2.6

#8064 Fix the vars
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#8068 Fix admin login
  ci/test-app
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl
  geoportal/tests/test_init.py
Labels: backport master

#8071 Fix schema path
  doc/integrator/tilegeneration.rst.tmpl
Labels: backport 2.6

#8070 Update c2c.template and sentry
  Pipfile
  Pipfile.lock
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#8074 Do spell on pull request title
  .github/workflows/pr-title-lint.yaml
  .github/workflows/pull-request-title.yaml
Labels: backport 2.4, backport 2.5, backport master, backport ngeo

#8099 Fix markers URL in the new applications
  build.mk
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static/images/markers/marker-blue.png
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static/images/markers/marker-gold.png
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static/images/markers/marker-green.png
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static/images/markers/marker.png
Labels: backport master

#8117 Be able to change the print URL for different organisations
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/views/printproxy.py
Labels: backport master

#8144 Separate with a dash like in GitHub workflows
  geoportal/c2cgeoportal_geoportal/scaffolds/create/ci/config.yaml_tmpl
Labels: backport master

#8160 Fix typo in doc
  doc/integrator/structure.rst
Labels: backport master
