Repository camptocamp/c2cgeoportal, pull requests merged in 2021-01, with the labels that each got.

#7579 Fix round on too big value
  geoportal/c2cgeoportal_geoportal/views/raster.py
  geoportal/tests/test_raster.py
Labels: backport 2.4, backport master

#7625 Fix shortener in dev mode
  geoportal/c2cgeoportal_geoportal/views/shortener.py
  geoportal/tests/functional/test_shortener.py
Labels: backport 2.4, backport 2.5

#7632 CI will fail on failed backport
  .github/workflows/main.yaml
  ci/config.yaml
Labels: backport 2.4, backport 2.5, backport ngeo

#7674 Update doc copyright
  doc/conf.py
Labels: backport master

#7684 Update demo external OGC servers
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master

#7714 Documentation: fix typos regarding names
  doc/integrator/api.rst
  doc/integrator/internationalization.rst
  doc/integrator/ngeo.rst.mako
Labels: backport 2.5, backport master
