Repository camptocamp/c2cgeoportal, pull requests merged in 2021-06, with the labels that each got.

#8305 Add asserts to be sure that the messageid are not None
  geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
Labels: backport master

#8296 Fix build with BuildKit
  geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
Labels: backport 2.6

#8311 Allow override theme mixed property in projects
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport 2.6, backport master

#8297 Add optional suffix in l10n
  bin/build-l10n
  doc/integrator/internationalization.rst
Labels: backport master

#8325 Fix issue with Different localisation sets
  bin/build-l10n
  doc/integrator/internationalization.rst
Labels: backport master

#8302 Fix encoding issue for QGIS projects in database
  commons/c2cgeoportal_commons/lib/url.py
  commons/tests/lib/test_url.py
  doc/integrator/backend_qgis.rst
Labels: backport master

#8344 Fix l10n, see commits
  bin/build-l10n
Labels: backport master

#8337 Don't copy the pot files in the container
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+dockerignore_tmpl
Labels: backport master

#8345 Remove extra emptyfolder
  geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
Labels: backport master

#8366 Fix error when we introduce a tab
  .github/workflows/qgis.yaml
  geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py
Labels: backport 2.4, backport 2.5, backport master

#8394 Copy the UI metadata from ngeo, to be able to find them with the search
  doc/administrator/administrate.rst.tmpl
Labels: backport master

#8400 Send MapServer substitution only on MapServer with standard auth
  geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
Labels: backport 2.5, backport 2.6

#8336 Remove unused vars section
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
Labels: backport master

#8416 Send MapServer substitution only on MapServer with standard auth
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport 2.6, backport master

#8417 Fix the child layers on groups
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport master
