Repository camptocamp/c2cgeoportal, pull requests merged in 2021-02, with the labels that each got.

#7722 Fix config.yaml path in urllogin script
  geoportal/c2cgeoportal_geoportal/scripts/urllogin.py
Labels: backport 2.5

#7705 Use WMS version from OGC server URL to GetCapabilities
  geoportal/c2cgeoportal_geoportal/lib/__init__.py
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/tests/functional/test_themes_mixed.py
Labels: backport 2.6

#7757 Bump c2cciutils
  ci/requirements.txt
Labels: backport 2.5

#7765 Fix upgrade to an rc
  geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Labels: backport 2.6, backport master

#7766 Make config enable_admin_interface scalar
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
Labels: backport 2.5, backport 2.6

#7805 Add some more generation commands
  geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/tilegeneration/config.yaml.tmpl_tmpl
Labels: backport master

#7830 Fix trigger for new version of gopass
  geoportal/c2cgeoportal_geoportal/scaffolds/create/ci/trigger
Labels: backport master

#7812 Add missing HELM_RELEASE_NAMES
  geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/main.yaml_tmpl
Labels: backport master

#7719 Replace pipenv install by pipenv sync
  Makefile
Labels: backport 2.5

#7826 Fix the upgrade to an rc
  scripts/upgrade
Labels: backport master

#7833 Set trigger as executable
  geoportal/c2cgeoportal_geoportal/scaffolds/__init__.py
Labels: backport master

#7839 Pull the major version
  scripts/upgrade
Labels: backport master

#7846 Fix executable
  geoportal/c2cgeoportal_geoportal/scaffolds/__init__.py
Labels: backport master
