Repository camptocamp/c2cgeoportal, pull requests merged in 2022-09, with the labels that each got.

#9378 Upgrade to `debugpy`
  doc/developer/debugging.rst
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/requirements.txt
Labels: backport master, backport 2.7

#10032 Update the Renovate configuration
  .github/renovate.json5
Labels: chore

#10031 Remove old Dependabot configuration
  .github/dependabot.yaml
Labels: chore

#10029 Fix the c2cwsgiutils base path when VISIBLE_ENTRY_POINT is not /
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master
