Repository camptocamp/c2cgeoportal, pull requests merged in 2022-03, with the labels that each got.

#9358 Don't have all the config in the cache key
  geoportal/c2cgeoportal_geoportal/lib/oauth2.py
Labels: backport 2.6

#9368 Remove default value for C2C_SECRET
  geoportal/c2cgeoportal_geoportal/scaffolds/create/env.project_tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Labels: backport master, backport 2.5

#9419 Fix CVE on url-parse, ignore CVE on angular-gettext-tools
  npm-cve-ignore
  package.json
Labels: backport 2.6

#9440 Ignore CVE on angular-gettext-tools
  ci/config.yaml
  npm-cve-ignore
Labels: backport master, backport 2.6

#9490 Have a red crosshare by default
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master
