Repository camptocamp/c2cgeoportal, pull requests merged in 2022-12, with the labels that each got.

#10214 Configure Mend Bolt
  .editorconfig
  .whitesource
Labels: chore

#10219 Configure Renovate to run monthly
  .github/renovate.json5
Labels: chore

#10237 Create the pull request for Snyk fix with the gs bot user
  .github/workflows/audit.yaml
Labels: chore

#10238 Be more standalone by default
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.github/workflows/main.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/tilegeneration/config.yaml.tmpl
Labels: backport master

#10243 Disable the auditing in the development branch (master)
  .github/workflows/audit.yaml
  ci/config.yaml
Labels: chore

#10242 Add variable content_security_policy_iframe_api_frame_ancestors
  geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Labels: backport master, backport 2.7
