Repository camptocamp/c2cgeoportal, pull requests merged in 2022-08, with the labels that each got.

#9941 Fix the rebuild by removing the coverage
  .github/workflows/rebuild-2-5.yaml
  .github/workflows/rebuild-2-6.yaml
Labels: dependencies

#9950 Add missing authentication in update_paths
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
Labels: backport master

#9953 Should work on Python 3.5
  .github/workflows/main.yaml
  doc/integrator/requirements.rst
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-backup
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-restore
  scripts/get-version
  scripts/upgrade
Labels: backport master

#9951 Add missing Vary on Cookie for private query
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/lib/caching.py
  geoportal/c2cgeoportal_geoportal/lib/common_headers.py
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
  geoportal/c2cgeoportal_geoportal/views/dynamic.py
  geoportal/c2cgeoportal_geoportal/views/entry.py
  geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py
  geoportal/c2cgeoportal_geoportal/views/i18n.py
  geoportal/c2cgeoportal_geoportal/views/layers.py
  geoportal/c2cgeoportal_geoportal/views/login.py
  geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
  geoportal/c2cgeoportal_geoportal/views/pdfreport.py
  geoportal/c2cgeoportal_geoportal/views/printproxy.py
  geoportal/c2cgeoportal_geoportal/views/profile.py
  geoportal/c2cgeoportal_geoportal/views/proxy.py
  geoportal/c2cgeoportal_geoportal/views/raster.py
  geoportal/c2cgeoportal_geoportal/views/resourceproxy.py
  geoportal/c2cgeoportal_geoportal/views/shortener.py
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
  geoportal/c2cgeoportal_geoportal/views/vector_tiles.py
  geoportal/tests/functional/test_login.py
  geoportal/tests/functional/test_oauth2.py
  geoportal/tests/test_caching.py
Labels: backport master

#9960 Remove WFS support of wms.geo.admin.ch
  .github/workflows/main.yaml
  geoportal/tests/functional/test_themes_mixed.py
Labels: backport master, backport 2.6, backport 2.7

#9965 Install wheel required for publishing
  .github/workflows/main.yaml
Labels: backport master

#9981 Clarify update_path example in the CHANGELOG
  geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Labels: backport master, backport 2.7
