Repository camptocamp/c2cgeoportal, pull requests merged in 2022-06, with the labels that each got.

#9781 Add simple auth support for OAuth2
  Pipfile
  Pipfile.lock
  geoportal/c2cgeoportal_geoportal/lib/oauth2.py
Labels: backport master

#9821 Better performances to create the theme when we are logged in
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/tests/functional/test_themes_entry.py
  geoportal/tests/functional/test_themes_loop.py
Labels: backport master

#9831 Don't call pickle on memory cache
  geoportal/c2cgeoportal_geoportal/lib/caching.py
Labels: backport master

#9852 We must not define a ng-app if we want to use the custom dynamic inje…
  doc/integrator/ngeo_new_interface.rst
Labels: backport master

#9854 Fix the publish from ngeo
  .github/workflows/main.yaml
  .github/workflows/ngeo-2-6.yaml
  .github/workflows/ngeo-2-7.yaml
  .github/workflows/rebuild-2-7.yaml
  doc/developer/build_release.rst
Labels: backport 2.7

#9878 Increase the Redis timeout
  geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl
Labels: backport master, backport 2.7

#9889 Fix the editing
  geoportal/c2cgeoportal_geoportal/views/layers.py
Labels: backport master, backport 2.7
