Repository camptocamp/c2cgeoportal, pull requests merged in 2022-10, with the labels that each got.

#10068 Fix the checkout user to be able to create pull request for Snyk fix
  .github/workflows/audit.yaml
Labels: chore

#10030 Add information about URL of external layers in changelog.
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
Labels: backport master

#10074 Add files that should not be installed
  ci/config.yaml
Labels: backport 2.7

#10094 Create audit workdlow, fix
  .editorconfig
  .github/workflows/main.yaml
  .tool-versions
  ci/.snyk
  ci/config.yaml
  docker/build/.snyk
  geoportal/.snyk
Labels: backport 2.5, backport 2.6

#10108 Add missing environment variables
  doc/integrator/extend_application.rst
Labels: backport master

#10114 Add workflow to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore

#10121 Fix repository in workflow used to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore
