Repository camptocamp/c2cgeoportal, pull requests merged in 2023-07, with the labels that each got.

#10565 Add call to request.user in Entry.get_ngeo_index_vars
  geoportal/c2cgeoportal_geoportal/views/entry.py
Labels: backport master, backport 2.8

#10581 Add content-security-policy for Google Analytics 4
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master, backport 2.8

#10584 Upgrade used Ubuntu version in the CI
  .github/workflows/ngeo-2-7.yaml
  .github/workflows/ngeo-2.8.yaml
  .github/workflows/rebuild-2-7.yaml
  .github/workflows/rebuild-2.8.yaml
  .github/workflows/rebuild-qgis-2-7.yaml
  .github/workflows/rebuild-qgis-2.8.yaml
Labels: backport 2.7, backport 2.8

#10591 [Doc Admin] Add a note for layer with no template
  doc/administrator/mapfile.rst
Labels: backport 2.7, backport 2.8

#10599 Referrer, while orthographically correct, is not the parameter name a…
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/print/print-apps/{{cookiecutter.package}}/config.yaml.tmpl
Labels: backport 2.8

#10608 Add editingSelectionAttribute metadata for edition popup selection
  admin/config.yaml
  admin/tests/tests.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master, backport 2.8

#10600 The configuration of the gunicorn.access logger will hide the access …
  geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/Dockerfile
  geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/gunicorn.conf.py
Labels: backport master, backport 2.8
