Repository camptocamp/c2cgeoportal, pull requests merged in 2023-06, with the labels that each got.

#10542 Fix CVE
  Pipfile
  Pipfile.lock
Labels: backport 2.8

#10548 Add qgis-3-28 to gmf-2-7
  .github/workflows/qgis.yaml
  docker/qgisserver/python/3.10/Pipfile
  docker/qgisserver/python/3.10/Pipfile.lock
Labels: backport master, enhancement, backport 2.8

#10547 Add qgis-3-28 to gmf-2-7
  .github/workflows/rebuild-qgis-2-7.yaml
Labels: backport 2.7, enhancement

#10554 Constrain the resolution
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master

#10559 Set default gmfOptions in all interfaces
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master

#10561 Add missing update_paths on gmfOptions
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
Labels: backport master

#10563 The resolutions should corresponds
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
Labels: backport master
