Repository camptocamp/c2cgeoportal, pull requests merged in 2023-10, with the labels that each got.

#10778 Fix changelog
  ci/changelog
  ci/changelog.yaml
Labels: backport master

#10780 The expiration is for the access token, not for the refresh token
  geoportal/c2cgeoportal_geoportal/lib/oauth2.py
Labels: backport master, backport 2.7, backport 2.8

#10787 Frame ancestors explanations
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
Labels: backport master, backport 2.8
