Repository camptocamp/c2cgeoportal, pull requests merged in 2023-03, with the labels that each got.

#10374 Improve LiDAR changelog
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
Labels: backport master

#10375 GEO-6299: Update editing.rst
  doc/administrator/editing.rst
Labels: backport 2.7, backport 2.8

#10388 Stronger update po
  geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile
Labels: backport master, backport 2.8

#10389 Add more documentation for hiDPILegendImages
  admin/config.yaml
  admin/tests/tests.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master, backport 2.8

#10395 Remove Snyk pinning
  docker/config/requirements.txt
Labels: chore

#10398 Update precommit hooks
  .pre-commit-config.yaml
  README.md
Labels: chore, backport 2.8

#10401 Fix new error with attr in pull request check workflow
  .github/workflows/pr-checks.yaml
Labels: chore

#10408 Improve the application reload
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
Labels: backport master

#10422 Remove double _alt in appName
  bin/import-ngeo-apps
Labels: backport master, backport 2.8

#10426 Retry when getting the pot
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile
Labels: backport master, backport 2.7

#10418 Publish and use the images x.y.z instead of x.y to be able to publish…
  .github/workflows/main.yaml
  Dockerfile
  Makefile
  ci/create-new-project
  geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/cookiecutter.json
  geoportal/c2cgeoportal_geoportal/scaffolds/advance_update/cookiecutter.json
  geoportal/c2cgeoportal_geoportal/scaffolds/create/cookiecutter.json
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/env.default
  geoportal/c2cgeoportal_geoportal/scaffolds/update/cookiecutter.json
  geoportal/c2cgeoportal_geoportal/scripts/pcreate.py
  scripts/get-version
Labels: backport 2.8

#10439 Fix major minor version
  scripts/get-version
Labels: backport master
