Repository camptocamp/c2cgeoportal, pull requests merged in 2024-08, with the labels that each got.

#11294 Fix Docker Compose version 2
  ci/test-app
Labels: backport 2.8

#11295 Fix upgrade for Docker Compose version 2
  scripts/upgrade
Labels: backport master, backport 2.7, backport 2.8

#10944 Remove wrong preload option
  geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/gunicorn.conf.py
Labels: backport 2.7, backport 2.8

#11339 Allow layers with special characters to be displayed in the theme
  geoportal/c2cgeoportal_geoportal/views/theme.py
Labels: backport master
