Repository camptocamp/c2cgeoportal, pull requests merged in 2024-11, with the labels that each got.

#11506 Also invalidate the ogc-server cache
  geoportal/c2cgeoportal_geoportal/__init__.py
Labels: backport master

#11512 The used id is required
  geoportal/c2cgeoportal_geoportal/lib/oidc.py
Labels: backport master

#11524 Force to use https in dev mode
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml
Labels: backport master, backport 2.8, backport 2.9

#11529 Fix force to use https in dev mode
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml
Labels: backport 2.8

#11535 Add OGC API Features support
  .github/workflows/main.yaml
  ci/docker-compose.override.yaml
  ci/mapserver.conf
  ci/test-app
  ci/vars.yaml
  doc/integrator/configuration.rst
  doc/integrator/ogc_api.rst
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/tests/test_app.py
  geoportal/c2cgeoportal_geoportal/scripts/create_demo_theme.py
  geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
Labels: backport master

#11547 Add missing cors view of the themes view
  geoportal/c2cgeoportal_geoportal/__init__.py
  geoportal/c2cgeoportal_geoportal/lib/common_headers.py
  geoportal/tests/functional/test_login.py
  geoportal/tests/functional/test_oauth2.py
  geoportal/tests/test_caching.py
Labels: backport master

#11536 Add QGIS supported version
  doc/integrator/authentication_oidc.rst
Labels: backport master

#11555 OGC API feature last fix and documentation
  doc/integrator/authentication_oidc.rst
  doc/integrator/ogc_api.rst
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/mapserver/mapserver.map.tmpl
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
Labels: backport master
