Repository camptocamp/c2cgeoportal, pull requests merged in 2024-12, with the labels that each got.

#11572 Get profile and height from service
  doc/integrator/raster.rst
  geoportal/c2cgeoportal_geoportal/views/profile.py
  geoportal/c2cgeoportal_geoportal/views/raster.py
Labels: backport 2.9

#11573 Remove cache-control switch from private to public
  geoportal/c2cgeoportal_geoportal/lib/common_headers.py
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
  geoportal/tests/functional/test_mapserverproxy.py
  geoportal/tests/functional/test_oauth2.py
  geoportal/tests/test_caching.py
Labels: backport master

#11578 Update used MapServer version
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml
Labels: backport master

#11577 Create a dedicated page for the authentication
  doc/integrator/authentication.rst
  doc/integrator/authentication_oauth2.rst
  doc/integrator/authentication_oidc.rst
  doc/integrator/index.rst
  doc/integrator/security.rst
Labels: backport master

#11581 Mapserver: Add oga_onlineresource for OGCAPI support
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/mapserver/mapserver.map.tmpl
Labels: backport master

#11574 Add possibility to add additional parameters to login end-point
  admin/c2cgeoportal_admin/views/layertree.py
  doc/integrator/authentication_oidc.rst
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_config-schema.yaml
  geoportal/c2cgeoportal_geoportal/views/dev.py
  geoportal/c2cgeoportal_geoportal/views/dynamic.py
  geoportal/c2cgeoportal_geoportal/views/entry.py
  geoportal/c2cgeoportal_geoportal/views/geometry_processing.py
  geoportal/c2cgeoportal_geoportal/views/i18n.py
  geoportal/c2cgeoportal_geoportal/views/layers.py
  geoportal/c2cgeoportal_geoportal/views/login.py
  geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
  geoportal/c2cgeoportal_geoportal/views/memory.py
  geoportal/c2cgeoportal_geoportal/views/pdfreport.py
  geoportal/c2cgeoportal_geoportal/views/printproxy.py
  geoportal/c2cgeoportal_geoportal/views/profile.py
  geoportal/c2cgeoportal_geoportal/views/raster.py
  geoportal/c2cgeoportal_geoportal/views/resourceproxy.py
  geoportal/c2cgeoportal_geoportal/views/shortener.py
  geoportal/c2cgeoportal_geoportal/views/theme.py
  geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
  geoportal/c2cgeoportal_geoportal/views/vector_tiles.py
Labels: backport master

#11589 Fix call to '/static'
  geoportal/c2cgeoportal_geoportal/lib/cacheversion.py
Labels: backport master

#11585 Replace epsg.io by pyproj
  geoportal/c2cgeoportal_geoportal/scripts/pcreate.py
Labels: backport master

#11593 Documentation: add information about QGIS protected attributes
  doc/integrator/backend_qgis.rst
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/.CONST_vars.yaml.swp
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport 2.9

#11598 Don't have an authenticatication loop
  geoportal/c2cgeoportal_geoportal/views/login.py
Labels: backport master

#11602 Fix simple application creation
  doc/integrator/create_application.rst
Labels: backport master, backport 2.9
