Repository camptocamp/c2cgeoportal, pull requests merged in 2025-09, with the labels that each got.

#12220 Remove node_modules, fix tools-cleaned, add packages that should be managed
  .github/workflows/qgis.yaml
  Dockerfile
  ci/dpkg-versions.yaml
  docker/qgisserver/Dockerfile
  docker/qgisserver/docker-compose.yaml
  poetry.lock
  pyproject.toml
Labels: backport master, backport 2.7, backport 2.8

#12236 Don't clean testing from commons
  Dockerfile
Labels: backport master, backport 2.7, backport 2.9

#12266 Don't print an exception on CTRL+C during build
  geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
Labels: backport 2.9

#12267 Handle deactivated user on password change
  geoportal/c2cgeoportal_geoportal/views/login.py
Labels: backport 2.8, backport 2.9
