Repository camptocamp/c2cgeoportal, pull requests merged in 2025-01, with the labels that each got.

#11629 Improve documentation for QGIS backend configuration
  doc/integrator/backend_qgis.rst
Labels: backport master

#11634 Add a venv to fix build of QGIS master
  .github/workflows/qgis.yaml
  ci/dpkg-versions.yaml
  ci/requirements.txt
  docker/qgisserver/Dockerfile
Labels: backport master

#11633 Add a global success marker
  .github/workflows/qgis.yaml
Labels: backport master, backport 2.7, backport 2.8

#11643 Fix small cache poisoning
  geoportal/c2cgeoportal_geoportal/views/dynamic.py
Labels: backport master, backport 2.6, backport 2.7, backport 2.8

#11672 Be more fluent, helped with Claude
  geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Labels: backport master

#11680 Fix unexpected error
  bin/eval-templates
Labels: backport master, backport 2.9
